famous_people = [
    {"name":"Kylie Jenner","country":"USA", "followers":1205000000, "profession":"Entrepreneur"},
    {"name":"Cristiano Ronaldo","country":"Portugal", "followers":1029000000, "profession":"Athlete"},
    {"name":"Selena Gomez","country":"USA", "followers":693000000, "profession":"Actress"},
    {"name":"Dwayne Johnson","country":"USA", "followers":645000000, "profession":"Actor"},
    {"name":"Ariana Grande","country":"USA", "followers":619000000, "profession":"Singer"},
    {"name":"Kendall Jenner","country":"USA", "followers":595000000, "profession":"Model"},
    {"name":"Kim Kardashian West","country":"USA", "followers":576000000, "profession":"Entrepreneur"},
    {"name":"Leo Messi","country":"Argentina", "followers":526000000, "profession":"Athlete"},
    {"name":"Beyoncé","country":"USA", "followers":506000000, "profession":"Singer"},
    {"name":"Justin Bieber","country":"Canada", "followers":503000000, "profession":"Singer"},
    {"name":"Taylor Swift","country":"USA", "followers":490000000, "profession":"Singer"},
    {"name":"Neymar Jr.","country":"Brazil", "followers":447000000, "profession":"Athlete"},
    {"name":"National Geographic","country":"USA", "followers":419000000, "profession":"Publication"},
    {"name":"Paul Pogba","country":"France", "followers":412000000, "profession":"Athlete"},
    {"name":"J Balvin","country":"Colombia", "followers":411000000, "profession":"Singer"},
    {"name":"Nicki Minaj","country":"USA", "followers":409000000, "profession":"Rapper"},
    {"name":"Shakira","country":"Colombia", "followers":397000000, "profession":"Singer"},
    {"name":"Lionel Messi","country":"Argentina", "followers":390000000, "profession":"Athlete"},
    {"name":"Khloe Kardashian","country":"USA", "followers":372000000, "profession":"Entrepreneur"},
    {"name":"Miley Cyrus","country":"USA", "followers":358000000, "profession":"Musician"},
    {"name":"Lil Nas X","country":"USA", "followers":328000000, "profession":"Musician"},
    {"name":"Justin Timberlake","country":"USA", "followers":323000000, "profession":"Musician"},
    {"name":"Chrissy Teigen","country":"USA", "followers":313000000, "profession":"Model"},
    {"name":"Adele","country":"UK", "followers":312000000, "profession":"Singer"},
    {"name":"Drake","country":"Canada", "followers":309000000, "profession":"Rapper"},
    {"name":"Kourtney Kardashian","country":"USA", "followers":308000000, "profession":"Entrepreneur"},
    {"name":"Lil Wayne","country":"USA", "followers":306000000, "profession":"Rapper"},
    {"name":"Jennifer Lopez","country":"USA", "followers":306000000, "profession":"Actress"},
    {"name":"Rihanna","country":"Barbados", "followers":305000000, "profession":"Singer"},
    {"name":"Serena Williams","country":"USA", "followers":292000000, "profession":"Athlete"},
    {"name":"Will Smith","country":"USA", "followers":289000000, "profession":"Actor"},
    {"name":"Kevin Hart","country":"USA", "followers":288000000, "profession":"Actor"},
    {"name":"Bruno Mars","country":"USA", "followers":287000000, "profession":"Singer"},
    {"name":"The Rock","country":"USA", "followers":283000000, "profession":"Actor"},
    {"name":"Kanye West","country":"USA", "followers":278000000, "profession":"Rapper"},
    {"name":"Conor McGregor","country":"Ireland", "followers":276000000, "profession":"Athlete"},
    {"name":"Ellen DeGeneres","country":"USA", "followers":271000000, "profession":"Actress"},
    {"name":"David Beckham","country":"UK", "followers":266000000, "profession":"Athlete"},
    {"name":"Demi Lovato","country":"USA", "followers":265000000, "profession":"Singer"},
    {"name":"Beyoncé","country":"USA", "followers":261000000, "profession":"Singer"},
    {"name":"J.K. Rowling","country":"UK", "followers":259000000, "profession":"Author"},
    {"name":"Kylie Jenner","country":"USA", "followers":256000000, "profession":"Entrepreneur"},
    {"name":"Huda Kattan","country":"USA", "followers":254000000, "profession":"Entrepreneur"},
    {"name":"Vanessa Hudgens","country":"USA", "followers":252000000, "profession":"Actress"},
    {"name":"Victoria Beckham","country":"UK", "followers":250000000, "profession":"Entrepreneur"},
    {"name":"Nick Jonas","country":"USA", "followers":249000000, "profession":"Musician"},
    {"name":"Joey Graceffa","country":"USA", "followers":249000000, "profession":"YouTuber"},
    {"name":"Cara Delevingne","country":"UK", "followers":248000000, "profession":"Model"},
    {"name":"The Weeknd","country":"Canada", "followers":241000000, "profession":"Singer"},
    {"name":"Mariah Carey","country":"USA", "followers":238000000, "profession":"Singer"},
    {"name":"Kris Jenner","country":"USA", "followers":237000000, "profession":"Entrepreneur"},
    {"name":"Selena Gomez","country":"USA", "followers":237000000, "profession":"Actress"},
    {"name":"Drake","country":"Canada", "followers":236000000, "profession":"Rapper"},
    {"name":"Kendall Jenner","country":"USA", "followers":234000000, "profession":"Model"},
    {"name":"Cardi B","country":"USA", "followers":231000000, "profession":"Rapper"},
    {"name":"Harry Styles","country":"UK", "followers":229000000, "profession":"Musician"},
    {"name":"Lily Collins","country":"UK", "followers":219000000, "profession":"Actress"},
    {"name":"Khloé Kardashian","country":"USA", "followers":214000000, "profession":"Entrepreneur"},
    {"name":"Kanye West","country":"USA", "followers":213000000, "profession":"Rapper"},
    {"name":"Zac Efron","country":"USA", "followers":212000000, "profession":"Actor"},
    {"name":"Dua Lipa","country":"UK", "followers":211000000, "profession":"Singer"},
    {"name":"Natalie Portman","country":"USA", "followers":208000000, "profession":"Actress"},
    {"name":"Nike","country":"USA", "followers":208000000, "profession":"Clothing Brand"},
    {"name":"Shawn Mendes","country":"Canada", "followers":207000000, "profession":"Musician"},
    {"name":"Niall Horan","country":"UK", "followers":206000000, "profession":"Musician"},
    {"name":"Justin Bieber","country":"Canada", "followers":205000000, "profession":"Singer"},
    {"name":"Cameron Dallas","country":"USA", "followers":204000000, "profession":"Actor"},
    {"name":"Lewis Hamilton","country":"UK", "followers":203000000, "profession":"Athlete"},
    {"name":"Zendaya","country":"USA", "followers":201000000, "profession":"Actress"},
    {"name":"Karlie Kloss","country":"USA", "followers":200000000, "profession":"Model"},
    {"name":"Kourtney Kardashian","country":"USA", "followers":199000000, "profession":"Entrepreneur"},
    {"name":"Katy Perry","country":"USA", "followers":198000000, "profession":"Singer"},
    {"name":"Zayn Malik","country":"UK", "followers":197000000, "profession":"Musician"},
    {"name":"Gigi Hadid","country":"USA", "followers":196000000, "profession":"Model"},
    {"name":"Liam Payne","country":"UK", "followers":196000000, "profession":"Musician"},
    {"name":"Ariana Grande","country":"USA", "followers":195000000, "profession":"Singer"},
    {"name":"Jennifer Aniston","country":"USA", "followers":194000000, "profession":"Actress"},
    {"name":"Rita Ora","country":"UK", "followers":193000000, "profession":"Singer"},
    {"name":"Kim Kardashian West","country":"USA", "followers":191000000, "profession":"Entrepreneur"},
    {"name":"Blake Lively","country":"USA", "followers":189000000, "profession":"Actress"},
    {"name":"J. Cole","country":"USA", "followers":188000000, "profession":"Rapper"},
    {"name":"Lady Gaga","country":"USA", "followers":186000000, "profession":"Singer"},
    {"name":"Bad Bunny","country":"Puerto Rico", "followers":185000000, "profession":"Musician"},
    {"name":"Marshmello","country":"USA", "followers":182000000, "profession":"DJ"},
    {"name":"Cristiano Ronaldo","country":"Portugal", "followers":181000000, "profession":"Athlete"},
    {"name":"Maluma","country":"Colombia", "followers":180000000, "profession":"Musician"},
    {"name":"Anitta","country":"Brazil", "followers":178000000, "profession":"Singer"},
    {"name":"Gisele Bündchen","country":"Brazil", "followers":176000000, "profession":"Model"},
    {"name":"Travis Scott","country":"USA", "followers":175000000, "profession":"Rapper"},
    {"name":"LeBron James","country":"USA", "followers":173000000, "profession":"Athlete"},
    {"name":"Hailey Bieber","country":"USA", "followers":172000000, "profession":"Model"},
    {"name":"John Cena","country":"USA", "followers":169000000, "profession":"Actor"},
    {"name":"Alok","country":"Brazil", "followers":169000000, "profession":"DJ"},
    {"name":"Dove Cameron","country":"USA", "followers":168000000, "profession":"Actress"},
    {"name":"Robert Downey Jr.","country":"USA", "followers":167000000, "profession":"Actor"},
    {"name":"Charlie Puth","country":"USA", "followers":165000000, "profession":"Musician"},
    {"name":"Kris Wu","country":"China", "followers":164000000, "profession":"Actor"},
    {"name":"Kevin Hart","country":"USA", "followers":163000000, "profession":"Actor"},
    {"name":"Kylie Jenner","country":"USA", "followers":162000000, "profession":"Entrepreneur"},
    {"name":"Camila Cabello","country":"Cuba", "followers":161000000, "profession":"Singer"},
    {"name":"Ed Sheeran","country":"UK", "followers":160000000, "profession":"Musician"},
    {"name":"Khloe Kardashian","country":"USA", "followers":157000000, "profession":"Entrepreneur"},
    {"name":"Real Madrid C.F.","country":"Spain", "followers":157000000, "profession":"Sports Team"},
    {"name":"Sofia Richie","country":"USA", "followers":156000000, "profession":"Model"},
    {"name":"Rihanna","country":"Barbados", "followers":155000000, "profession":"Singer"},
    {"name":"Gigi Gorgeous","country":"Canada", "followers":155000000, "profession":"Model"},
    {"name":"Kevin Durant","country":"USA", "followers":154000000, "profession":"Athlete"},
    {"name":"Zara Larsson","country":"Sweden", "followers":153000000, "profession":"Singer"},
    {"name":"Neymar Jr.","country":"Brazil", "followers":152000000, "profession":"Athlete"},
    {"name":"Virat Kohli","country":"India", "followers":151000000, "profession":"Athlete"},
    {"name":"G-Eazy","country":"USA", "followers":150000000, "profession":"Rapper"},
    {"name":"Will Smith","country":"USA", "followers":149000000, "profession":"Actor"},
    {"name":"Stephen Curry","country":"USA", "followers":149000000, "profession":"Athlete"},
    {"name":"Miley Cyrus","country":"USA", "followers":148000000, "profession":"Musician"},
    {"name":"Dua Lipa","country":"UK", "followers":147000000, "profession":"Singer"},
    {"name":"Kylie Jenner","country":"USA", "followers":147000000, "profession":"Entrepreneur"},
    {"name":"Kendall Jenner","country":"USA", "followers":146000000, "profession":"Model"},
    {"name":"Kim Kardashian West","country":"USA", "followers":145000000, "profession":"Entrepreneur"},
    {"name":"Lil Nas X","country":"USA", "followers":145000000, "profession":"Musician"},
    {"name":"Shawn Mendes","country":"Canada", "followers":144000000, "profession":"Musician"},
    {"name":"The Rock","country":"USA", "followers":143000000, "profession":"Actor"},
    {"name":"Victoria Beckham","country":"UK", "followers":143000000, "profession":"Entrepreneur"},
    {"name":"Khloe Kardashian","country":"USA", "followers":141000000, "profession":"Entrepreneur"},
    {"name":"Justin Timberlake","country":"USA", "followers":141000000, "profession":"Musician"},
    {"name":"Cardi B","country":"USA", "followers":140000000, "profession":"Rapper"},
    {"name":"Drake","country":"Canada", "followers":139000000, "profession":"Rapper"},
    {"name":"Adele","country":"UK", "followers":139000000, "profession":"Singer"},
    {"name":"Harry Styles","country":"UK", "followers":138000000, "profession":"Musician"},
    {"name":"Chris Hemsworth","country":"USA", "followers":137000000, "profession":"Actor"},
    {"name":"Cara Delevingne","country":"UK", "followers":137000000, "profession":"Model"},
    {"name":"Lily Collins","country":"UK", "followers":135000000, "profession":"Actress"},
    {"name":"Kourtney Kardashian","country":"USA", "followers":135000000, "profession":"Entrepreneur"},
    {"name":"David Beckham","country":"UK", "followers":133000000, "profession":"Athlete"},
    {"name":"Kylie Jenner","country":"USA", "followers":131000000, "profession":"Entrepreneur"},
    {"name":"Kris Jenner","country":"USA", "followers":131000000, "profession":"Entrepreneur"},
    {"name":"Kanye West","country":"USA", "followers":130000000, "profession":"Rapper"},
    {"name":"Zendaya","country":"USA", "followers":130000000, "profession":"Actress"},
    {"name":"Karlie Kloss","country":"USA", "followers":129000000, "profession":"Model"},
    {"name":"Katy Perry","country":"USA", "followers":128000000, "profession":"Singer"},
    {"name":"Zayn Malik","country":"UK", "followers":128000000, "profession":"Musician"},
    {"name":"Gigi Hadid","country":"USA", "followers":127000000, "profession":"Model"},
    {"name":"Liam Payne","country":"UK", "followers":126000000, "profession":"Musician"},
    {"name":"Ariana Grande","country":"USA", "followers":125000000, "profession":"Singer"},
    {"name":"Jennifer Aniston","country":"USA", "followers":125000000, "profession":"Actress"},
    {"name":"Rita Ora","country":"UK", "followers":124000000, "profession":"Singer"},
    {"name":"Kim Kardashian West","country":"USA", "followers":124000000, "profession":"Entrepreneur"},
    {"name":"Lady Gaga","country":"USA", "followers":123000000, "profession":"Singer"},
    {"name":"Blake Lively","country":"USA", "followers":123000000, "profession":"Actress"},
    {"name":"J. Cole","country":"USA", "followers":122000000, "profession":"Rapper"},
    {"name":"Bad Bunny","country":"Puerto Rico", "followers":121000000, "profession":"Musician"},
    {"name":"Marshmello","country":"USA", "followers":121000000, "profession":"DJ"},
    {"name":"Cristiano Ronaldo","country":"Portugal", "followers":120000000, "profession":"Athlete"},
    {"name":"Maluma","country":"Colombia", "followers":120000000, "profession":"Musician"},
    {"name":"Anitta","country":"Brazil", "followers":118000000, "profession":"Singer"},
    {"name":"Gisele Bündchen","country":"Brazil", "followers":118000000, "profession":"Model"},
    {"name":"Travis Scott","country":"USA", "followers":118000000, "profession":"Rapper"},
    {"name":"LeBron James","country":"USA", "followers":117000000, "profession":"Athlete"},
    {"name":"Hailey Bieber","country":"USA", "followers":117000000, "profession":"Model"},
    {"name":"John Cena","country":"USA", "followers":117000000, "profession":"Actor"},
    {"name":"Alok","country":"Brazil", "followers":116000000, "profession":"DJ"},
    {"name":"Dove Cameron","country":"USA", "followers":116000000, "profession":"Actress"},
    {"name":"Robert Downey Jr.","country":"USA", "followers":115000000, "profession":"Actor"},
    {"name":"Charlie Puth","country":"USA", "followers":115000000, "profession":"Musician"},
    {"name":"Kris Wu","country":"China", "followers":115000000, "profession":"Actor"},
    {"name":"Camila Cabello","country":"Cuba", "followers":114000000, "profession":"Singer"},
    {"name":"Ed Sheeran","country":"UK", "followers":113000000, "profession":"Musician"},
    {"name":"Real Madrid C.F.","country":"Spain", "followers":113000000, "profession":"Sports Team"},
    {"name":"Sofia Richie","country":"USA", "followers":113000000, "profession":"Model"},
    {"name":"Rihanna","country":"Barbados", "followers":111000000, "profession":"Singer"},
    {"name":"Gigi Gorgeous","country":"Canada", "followers":111000000, "profession":"Model"},
    {"name":"Kevin Durant","country":"USA", "followers":111000000, "profession":"Athlete"},
    {"name":"Zara Larsson","country":"Sweden", "followers":111000000, "profession":"Singer"},
    {"name":"Neymar Jr.","country":"Brazil", "followers":110000000, "profession":"Athlete"},
    {"name":"Virat Kohli","country":"India", "followers":110000000, "profession":"Athlete"},
    {"name":"G-Eazy","country":"USA", "followers":109000000, "profession":"Rapper"},
    {"name":"Will Smith","country":"USA", "followers":109000000, "profession":"Actor"},
    {"name":"Stephen Curry","country":"USA", "followers":109000000, "profession":"Athlete"},
]
